#
# Site settings
#
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Riding on the wind
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "" # the base hostname & protocol for your site, e.g. http://example.com
github: [metadata] # Removes a warning emitted during a local build

#
# Build settings
#
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-feed
  - jekyll-include-cache

#
# Appearane, features, and structure
# (theme-dependent)
#

locale: en-GB
search: true
breadcrumbs: false
atom_feed:
  hide: true
minimal_mistakes_skin: "dirt"  # "default", "air", "aqua", "contrast", "dark",
                               # "dirt", "neon", "mint", "plum", "sunrise"
paginate: 5
paginate_path: /_pages/posts/page:num/

author:
  name: "Peter Matulis"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: true
      share: true
      related: false

# The next two stanzas are to make individual category and tag indices to work.
# Note that each category and tag will require its own file to be created
# manually. This is needed because the 'jekyll-archives' plugin is not
# installed due to some incompatibily with GitHub Pages. See files
# '/categories/compute.md' and '/tags/focal.md' for examples.

category_archive:
  type: jekyll-archives
  path: /categories/

tag_archive:
  type: jekyll-archives
  path: /tags/

#
# Exclude from processing
#
# The following items will not be processed, by default. Any item listed under
# the `exclude:` key here will be automatically added to the internal "default
# list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

include:
  - _pages
